# Generated by Django 2.1.7 on 2019-03-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=300)),
                ('description', models.TextField(default=' ')),
                ('SLT', models.TextField(default=' ')),
                ('threats', models.TextField(default=' ')),
            ],
        ),
    ]
