# Generated by Django 2.1.7 on 2019-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0003_auto_20190324_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zones',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='zoneId',
            field=models.TextField(default=' '),
        ),
    ]
