# Generated by Django 2.1.7 on 2019-04-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0005_auto_20190324_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(default=' ', max_length=300)),
                ('componentDescription', models.CharField(default=' ', max_length=300)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.Zones')),
            ],
        ),
    ]
