# Generated by Django 2.1.7 on 2019-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0006_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat', models.CharField(default=' ', max_length=300)),
                ('description', models.CharField(default=' ', max_length=500)),
                ('status', models.CharField(choices=[('InWork', 'In Work'), ('Approved', 'Approved'), ('Released', 'Released'), ('Obsolete', 'Obsolete')], max_length=1)),
                ('createdBy', models.CharField(default=' ', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='component',
            name='componentDescription',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='zones',
            name='name',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='threats',
            name='accordingZone',
            field=models.ManyToManyField(related_name='_threats_accordingZone_+', to='zone.Zones'),
        ),
    ]
