# Generated by Django 2.1.7 on 2019-04-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0007_auto_20190406_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(default=' ', max_length=300)),
                ('description', models.CharField(default=' ', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DamageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=' ', max_length=300)),
                ('damage', models.CharField(default=' ', max_length=300)),
                ('factor', models.IntegerField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damagePotential', models.IntegerField(default=' ')),
                ('impactLevel', models.IntegerField(default=' ')),
                ('impactPotential', models.IntegerField(default=' ')),
                ('impactCategory', models.CharField(default=' ', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LikeleyHood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeCategory', models.CharField(default=' ', max_length=300)),
                ('experienceCategory', models.CharField(default=' ', max_length=300)),
                ('knowledgeCategory', models.CharField(default=' ', max_length=300)),
                ('equipmentCategory', models.CharField(default=' ', max_length=300)),
                ('opportunityCategory', models.CharField(default=' ', max_length=300)),
                ('timeValue', models.IntegerField(default=' ')),
                ('experienceValue', models.IntegerField(default=' ')),
                ('knowledgeValue', models.IntegerField(default=' ')),
                ('equipmentValue', models.IntegerField(default=' ')),
                ('opportunityValue', models.IntegerField(default=' ')),
                ('impactCategory', models.CharField(default=' ', max_length=300)),
                ('impactLevel', models.IntegerField(default=' ')),
                ('totalImpact', models.IntegerField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolerableRisk', models.IntegerField(default=' ')),
                ('SLT', models.IntegerField(default=' ')),
                ('actualRisk', models.IntegerField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=300)),
                ('description', models.CharField(default=' ', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='threats',
            name='accordingZone',
        ),
        migrations.RemoveField(
            model_name='zones',
            name='SLT',
        ),
        migrations.RemoveField(
            model_name='zones',
            name='threats',
        ),
        migrations.AddField(
            model_name='threats',
            name='zone',
            field=models.ManyToManyField(related_name='_threats_zone_+', to='zone.Zones'),
        ),
        migrations.AlterField(
            model_name='threats',
            name='status',
            field=models.CharField(choices=[('InWork', 'In Work'), ('Approved', 'Approved'), ('Released', 'Released'), ('Obsolete', 'Obsolete')], max_length=20),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='threat',
            field=models.ManyToManyField(related_name='_vulnerability_threat_+', to='zone.Threats'),
        ),
        migrations.AddField(
            model_name='risks',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.Zones'),
        ),
        migrations.AddField(
            model_name='likeleyhood',
            name='risk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zone.Risks'),
        ),
        migrations.AddField(
            model_name='impact',
            name='risk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zone.Risks'),
        ),
        migrations.AddField(
            model_name='damagelist',
            name='impact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zone.Impact'),
        ),
        migrations.AddField(
            model_name='countermeasure',
            name='threat',
            field=models.ManyToManyField(related_name='_countermeasure_threat_+', to='zone.Threats'),
        ),
    ]
